/* 角色数据 v3 - 含 rarity + tags + 性格标签 */

/* ============================================================
 * 【老师专用】课堂口令配置
 * 孩子完成任务后找老师要口令，输入口令加分。
 * 每节课前可以随手改口令内容（改引号里的词就行，右边是分数）：
 *   回答对问题 → 给 +1 档口令
 *   积极思考   → 给 +2 档口令
 *   完成设计   → 给 +5 档口令
 *   完成制作   → 给 +10 档口令
 * 注意：同一个口令在同一台设备上只能兑换一次。
 * ============================================================ */
window.TEACHER_CODES = {
  '星河': 1,
  '萤火虫': 2,
  '彩虹桥': 5,
  '大力神': 10,
};

window.CHARACTERS = [
  {
    "id": "人物1",
    "name": "小朗",
    "gender": "男",
    "personality": "勇敢、自信、可靠",
    "intro": "金发小长枪手，红披风，眼神坚定又有礼",
    "hair": "金",
    "weapon": "长枪",
    "style": "骑士、帅气",
    "img": "assets/小朗.png",
    "rarity": "R",
    "tags": ["勇敢", "阳光", "自信"],
    "alts": ["阿凯", "雷恩"]
  },
  {
    "id": "人物2",
    "name": "小杰",
    "gender": "男",
    "personality": "开朗、勇敢、直率",
    "intro": "棕发小剑士，红衣亮眼，笑起来特别有精神",
    "hair": "棕",
    "weapon": "短剑",
    "style": "战士、阳光",
    "img": "assets/小杰.png",
    "rarity": "N",
    "tags": ["勇敢", "阳光", "直率"],
    "alts": ["阿烁", "炎诚"]
  },
  {
    "id": "人物3",
    "name": "小洛",
    "gender": "男",
    "personality": "认真、勇敢、正直",
    "intro": "棕发小剑士，手持长剑，表情认真又帅气",
    "hair": "棕",
    "weapon": "长剑",
    "style": "战士、帅气",
    "img": "assets/小洛.png",
    "rarity": "N",
    "tags": ["勇敢", "冷静", "正直"],
    "alts": ["阿凛", "诺诺"]
  },
  {
    "id": "图片1",
    "name": "小岚",
    "gender": "女",
    "personality": "勇敢、开朗、爱冒险",
    "intro": "红发小海盗，戴着羽毛帽，眼睛亮晶晶的",
    "hair": "红",
    "weapon": "无",
    "style": "冒险者、活泼",
    "img": "assets/小岚.png",
    "rarity": "SR",
    "tags": ["勇敢", "阳光", "调皮"],
    "alts": ["阿娜", "洛莉"]
  },
  {
    "id": "图片3",
    "name": "小雪",
    "gender": "女",
    "personality": "活泼、元气、有点调皮",
    "intro": "银发双马尾小女孩，扛着大锤子，萌力十足",
    "hair": "银",
    "weapon": "大锤",
    "style": "可爱、力气大",
    "img": "assets/小雪.png",
    "rarity": "R",
    "tags": ["调皮", "阳光", "可爱"],
    "alts": ["米娅", "琪琪"]
  },
  {
    "id": "图片4",
    "name": "小岩",
    "gender": "女",
    "personality": "豪爽、勇敢、直率",
    "intro": "深肤色的小斧战士，扎着高马尾，又飒又可爱",
    "hair": "棕灰",
    "weapon": "斧",
    "style": "野性、飒",
    "img": "assets/小岩.png",
    "rarity": "N",
    "tags": ["强壮", "勇敢", "直率"],
    "alts": ["阿棕", "砂砂"]
  },
  {
    "id": "图片5",
    "name": "小铃",
    "gender": "女",
    "personality": "温柔、可爱、勤劳",
    "intro": "金发猫耳小斧手，戴着软软帽子，眼神温柔",
    "hair": "金",
    "weapon": "斧",
    "style": "兽耳、温柔",
    "img": "assets/小铃.png",
    "rarity": "SR",
    "tags": ["可爱", "文静", "阳光"],
    "alts": ["米可", "朵朵"]
  },
  {
    "id": "图片6",
    "name": "小樱",
    "gender": "女",
    "personality": "开朗、勇敢、可爱",
    "intro": "棕发双马尾小剑士，穿红裙举长剑，笑容甜甜的",
    "hair": "棕",
    "weapon": "剑",
    "style": "甜美、双马尾",
    "img": "assets/小樱.png",
    "rarity": "N",
    "tags": ["可爱", "阳光", "勇敢"],
    "alts": ["红豆", "糖糖"]
  },
  {
    "id": "图片7",
    "name": "小夜",
    "gender": "女",
    "personality": "机灵、冷静、活泼",
    "intro": "灰紫色马尾小剑士，红衣利落，眼神透着机灵",
    "hair": "灰紫",
    "weapon": "剑",
    "style": "忍者风、利落",
    "img": "assets/小夜.png",
    "rarity": "R",
    "tags": ["调皮", "冷静", "神秘"],
    "alts": ["阿墨", "紫苑"]
  },
  {
    "id": "图片8",
    "name": "小糖",
    "gender": "女",
    "personality": "元气、爱笑、力气大",
    "intro": "棕发双马尾小锤手，举着大锤子笑得超甜",
    "hair": "棕",
    "weapon": "大锤",
    "style": "元气、彩色装",
    "img": "assets/小糖.png",
    "rarity": "N",
    "tags": ["调皮", "阳光", "可爱"],
    "alts": ["锤锤", "圆圆"]
  },
  {
    "id": "图片9",
    "name": "小羽",
    "gender": "男",
    "personality": "温和、沉静、有点神秘",
    "intro": "金发小弓手，头戴花冠，眼神清澈又温柔",
    "hair": "金",
    "weapon": "弓",
    "style": "希腊风、清秀",
    "img": "assets/小羽.png",
    "rarity": "SR",
    "tags": ["神秘", "文静", "冷静"],
    "alts": ["阿阳", "晨光"]
  },
  {
    "id": "图片10",
    "name": "小橙",
    "gender": "女",
    "personality": "认真、安静、爱学习",
    "intro": "橙发小法师，抱着魔法书，表情认真又乖巧",
    "hair": "橙",
    "weapon": "法书",
    "style": "文静、法师",
    "img": "assets/小橙.png",
    "rarity": "N",
    "tags": ["文静", "神秘", "调皮"],
    "alts": ["阿梨", "米洛"]
  },
  {
    "id": "图片11",
    "name": "小狸",
    "gender": "女",
    "personality": "调皮、敏捷、活泼",
    "intro": "粉发小游侠，甩着长尾巴，一脸俏皮又机灵",
    "hair": "粉",
    "weapon": "鞭/绳",
    "style": "俏皮、动物尾",
    "img": "assets/小狸.png",
    "rarity": "R",
    "tags": ["调皮", "神秘", "阳光"],
    "alts": ["阿果", "可可"]
  },
  {
    "id": "图片12",
    "name": "小苍",
    "gender": "男",
    "personality": "聪明、机灵、有点滑头",
    "intro": "绿发小游侠，嘴角带笑，看起来像个小机灵鬼",
    "hair": "绿",
    "weapon": "无",
    "style": "游侠、自信",
    "img": "assets/小苍.png",
    "rarity": "N",
    "tags": ["调皮", "神秘", "冷静"],
    "alts": ["阿青", "叶洛"]
  },
  {
    "id": "图片13",
    "name": "小银",
    "gender": "男",
    "personality": "冷静、神秘、睿智",
    "intro": "白发小法师，手握长杖，眼神冷静又神秘",
    "hair": "白",
    "weapon": "长杖",
    "style": "冷酷、法师",
    "img": "assets/小银.png",
    "rarity": "R",
    "tags": ["冷静", "神秘", "勇敢"],
    "alts": ["阿雪", "星羽"]
  },
  {
    "id": "图片14",
    "name": "小蓝",
    "gender": "女",
    "personality": "温柔、勇敢、单纯",
    "intro": "蓝发小枪士，手持长枪，眼神清澈又认真",
    "hair": "蓝",
    "weapon": "长枪",
    "style": "清纯、骑士",
    "img": "assets/小蓝.png",
    "rarity": "N",
    "tags": ["勇敢", "文静", "冷静"],
    "alts": ["阿涟", "海音"]
  },
  {
    "id": "图片15",
    "name": "铁铁",
    "gender": "不分",
    "personality": "稳重、忠诚、力量型",
    "intro": "方头小机器人，红眼睛闪闪，看起来超可靠",
    "hair": "无",
    "weapon": "无",
    "style": "机器人、机甲",
    "img": "assets/铁铁.png",
    "rarity": "SSR",
    "tags": ["强壮", "神秘", "冷静"],
    "alts": ["小甲", "机宝"]
  },
  {
    "id": "图片16",
    "name": "桃桃",
    "gender": "女",
    "personality": "温柔、善良、爱幻想",
    "intro": "粉发小法师，手持魔杖，背后像长了小翅膀一样可爱",
    "hair": "粉",
    "weapon": "魔杖",
    "style": "梦幻、翅膀装饰",
    "img": "assets/桃桃.png",
    "rarity": "SSR",
    "tags": ["可爱", "文静", "阳光"],
    "alts": ["粉粉", "樱子"]
  },
  {
    "id": "图片17",
    "name": "星弦",
    "gender": "男",
    "personality": "自信、勇敢、阳光",
    "intro": "金发小弓手，拉弓瞄准，神情专注又帅气",
    "hair": "金",
    "weapon": "弓",
    "style": "弓手、帅气",
    "img": "assets/星弦.png",
    "rarity": "R",
    "tags": ["勇敢", "阳光", "冷静"],
    "alts": ["阿弓", "小金"]
  },
  {
    "id": "图片18",
    "name": "小狼",
    "gender": "男",
    "personality": "热血、勇敢、狂野",
    "intro": "白发小剑士，头发像小刺猬，笑起来特别有冲劲",
    "hair": "白",
    "weapon": "剑",
    "style": "刺猬头、热血",
    "img": "assets/小狼.png",
    "rarity": "R",
    "tags": ["勇敢", "调皮", "阳光"],
    "alts": ["阿银", "烈风"]
  },
  {
    "id": "图片19",
    "name": "小卫",
    "gender": "男",
    "personality": "负责、严肃、可靠",
    "intro": "棕发小卫兵，身穿红衣戴帽子，站得笔直很精神",
    "hair": "棕",
    "weapon": "长矛",
    "style": "卫兵、认真",
    "img": "assets/小卫.png",
    "rarity": "N",
    "tags": ["勇敢", "冷静", "阳光"],
    "alts": ["阿诺", "小磊"]
  },
  {
    "id": "图片20",
    "name": "小锋",
    "gender": "男",
    "personality": "冷静、强大、沉稳",
    "intro": "银发小斧战士，扛着大斧，眼神冷静又霸气",
    "hair": "银",
    "weapon": "大斧",
    "style": "冷酷、黑甲",
    "img": "assets/小锋.png",
    "rarity": "SR",
    "tags": ["强壮", "冷静", "神秘"],
    "alts": ["阿斧", "雷恩"]
  },
  {
    "id": "图片21",
    "name": "小伦",
    "gender": "男",
    "personality": "勇敢、温和、正直",
    "intro": "棕发小骑士，蓝甲配长枪，笑容温和又可靠",
    "hair": "棕",
    "weapon": "长枪",
    "style": "骑士、蓝甲",
    "img": "assets/小伦.png",
    "rarity": "N",
    "tags": ["勇敢", "阳光", "冷静"],
    "alts": ["阿蓝", "小骑士"]
  },
  {
    "id": "图片22",
    "name": "阿力",
    "gender": "男",
    "personality": "开朗、豪爽、亲切",
    "intro": "棕发小斧手，扛着斧头笑得眼睛弯弯，看起来超亲切",
    "hair": "棕",
    "weapon": "斧",
    "style": "斧手、亲切",
    "img": "assets/阿力.png",
    "rarity": "R",
    "tags": ["阳光", "强壮", "调皮"],
    "alts": ["小斧", "笑笑"]
  },
  {
    "id": "图片23",
    "name": "小盾",
    "gender": "男",
    "personality": "忠诚、踏实、老实",
    "intro": "棕发小骑士，身穿银色盔甲，站得稳稳当当",
    "hair": "棕",
    "weapon": "无",
    "style": "骑士、稳重",
    "img": "assets/小盾.png",
    "rarity": "N",
    "tags": ["勇敢", "冷静", "强壮"],
    "alts": ["小铁", "守守", "阿盾"]
  },
  {
    "id": "图片24",
    "name": "小灰",
    "gender": "男",
    "personality": "冷静、专注、酷酷的",
    "intro": "灰发小弓手，银甲配长弓，表情酷酷的",
    "hair": "灰",
    "weapon": "长弓",
    "style": "银甲、冷酷",
    "img": "assets/小灰.png",
    "rarity": "R",
    "tags": ["冷静", "神秘", "勇敢"],
    "alts": ["阿羽", "冷星"]
  },
  {
    "id": "图片25",
    "name": "小夏",
    "gender": "男",
    "personality": "开朗、随性、友好",
    "intro": "橙发小男孩，穿着花衬衫，笑得像夏天的太阳",
    "hair": "橙",
    "weapon": "无",
    "style": "休闲、阳光",
    "img": "assets/小夏.png",
    "rarity": "R",
    "tags": ["阳光", "调皮", "神秘"],
    "alts": ["阿橙", "果林"]
  },
  {
    "id": "图片26",
    "name": "小焰",
    "gender": "男",
    "personality": "勇敢、认真、沉稳",
    "intro": "红紫发小骑士，披着红斗篷握长剑，神情认真又帅气",
    "hair": "红紫",
    "weapon": "长剑",
    "style": "骑士、帅气",
    "img": "assets/小焰.png",
    "rarity": "SR",
    "tags": ["勇敢", "阳光", "神秘"],
    "alts": ["阿紫", "焰焰"]
  },
  {
    "id": "图片27",
    "name": "阿木",
    "gender": "男",
    "personality": "害羞、努力、安静",
    "intro": "棕发小男孩，刘海遮住眼睛，握着小矛有点害羞",
    "hair": "棕",
    "weapon": "长矛",
    "style": "害羞、低调",
    "img": "assets/阿木.png",
    "rarity": "N",
    "tags": ["文静", "神秘", "可爱"],
    "alts": ["小土", "豆豆"]
  },
  {
    "id": "图片28",
    "name": "小烈",
    "gender": "男",
    "personality": "狂野、勇敢、强壮",
    "intro": "紫发小斧战士，红头带飘起来，抡起大斧特别有气势",
    "hair": "紫",
    "weapon": "大斧",
    "style": "勇猛、狂野",
    "img": "assets/小烈.png",
    "rarity": "R",
    "tags": ["强壮", "调皮", "勇敢"],
    "alts": ["岩岩", "阿战"]
  },
];